# fly.toml app configuration file generated for reshare-livekit on 2026-09-10T20:05:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reshare-livekit'
primary_region = 'gru'

[experimental]
  cmd = ['--config', '/etc/livekit/livekit.yaml']

[build]
  image = 'livekit/livekit-server:v1.9.1'

[[services]]
  protocol = 'tcp'
  internal_port = 7880
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 400
    soft_limit = 200

[[services]]
  protocol = 'udp'
  internal_port = 7882

  [[services.ports]]
    port = 7882

[[services]]
  protocol = 'tcp'
  internal_port = 7881

  [[services.ports]]
    port = 7881

[[services]]
  protocol = 'tcp'
  internal_port = 5349

  [[services.ports]]
    port = 5349
    handlers = ['tls']

[[files]]
  guest_path = '/etc/livekit/livekit.yaml'
  local_path = 'livekit.yaml'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
